services:
  postgres:
    image: postgres:16-alpine
    container_name: safecampus-db
    environment:
      POSTGRES_USER: safecampus
      POSTGRES_PASSWORD: safecampus123
      POSTGRES_DB: safecampus
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
